<?php


namespace app\common\jwt;


use app\common\jwt\Jwt;

class JwtValidationData extends \sizeg\jwt\JwtValidationData
{
    public function init()
    {
        $this->validationData->setId((new Jwt())->identifiedBy);
        parent::init(); // TODO: Change the autogenerated stub
    }

}
